[package]
name = "rustris"
version = "0.3.0"
authors = ["Justin LeFebvre <jstnlefebvre@gmail.com>"]

[dependencies]
conrod = "0.32.0"
find_folder = "0.3.0"
piston = "0.19.0"
piston_window = "0.38.0"
rand = "0.3.14"
