[package]
name = "rustris"
version = "0.5.0"
authors = ["Justin LeFebvre <jstnlefebvre@gmail.com>"]

[dependencies]
conrod = "0.34.0"
find_folder = "0.3.0"
piston = "0.20.0"
piston_window = "0.44.0"
rand = "0.3.14"
